services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "15432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  migrations:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: bash -c "alembic upgrade head && python -m src.core.scripts"

  web:
    build: .
    depends_on:
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    command: uvicorn src.main:app --host 0.0.0.0 --port ${PROJECT_PORT}
    ports:
      - "${PROJECT_PORT}:${PROJECT_PORT}"

  celery-beat:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    command: celery -A worker.celery_app beat --loglevel=info

  celery:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    command: celery -A worker.celery_app worker --loglevel=info

volumes:
  postgres_data: